### ISSUE TITLE
Github Actions Master Issue

### ISSUE THREAD

**Issue by James-Oswald** [James-Oswald/Direction-Guesser#10]
Create GitHub actions that:
- [x] Build the frontend into an artifact (preferably a .apk file) that can be deployed on a phone
- [x] Build the backend to an executable. 
- [x] Run in-source unit tests on the backend.
